spring:
  application:
    name: order

server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://192.168.0.71:8081/eureka/}