spring:
  application:
    name: zuul
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order/
          predicates:
            - Path=/app1/**
        - id: pay
          uri: lb://pay/
          predicates:
            - Path=/bpp1/**

server:
  port: 8765

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://192.168.0.71:8081/eureka/}