spring:
  application:
    name: server1

server:
  port: 8081

eureka:
  instance:
    hostname: 192.168.0.71
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false